name: Deploy
on: 
  push:
    branches:
      - master

jobs:
  buildAndDeploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Serverless Framework
        run: npm install -g serverless
      - name: Install node modules
        run: npm install
      - name: Serverless package
        run: serverless package -v -s dev
      - name: Build package
        run: |
            mkdir package
            cp serverless.yml package
            cp package.json package
            cp -r .serverless package/.serverless
            ls -al package
      - name: Zip package
        uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r serverless-output.zip package
      - name: Put package to S3
        uses: ItsKarma/aws-cli@v1.70.0
        with:
          args: s3 cp serverless-output.zip s3://team-2-deployment-deployment-source/deployment_package/serverless-output.zip --sse
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "eu-west-1"
